# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teds-sub-editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_auxWindow(object):
    def setupUi(self, auxWindow):
        auxWindow.setObjectName("auxWindow")
        auxWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(auxWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 761, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        auxWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(auxWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        auxWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(auxWindow)
        self.statusbar.setObjectName("statusbar")
        auxWindow.setStatusBar(self.statusbar)

        self.retranslateUi(auxWindow)
        QtCore.QMetaObject.connectSlotsByName(auxWindow)

    def retranslateUi(self, auxWindow):
        _translate = QtCore.QCoreApplication.translate
        auxWindow.setWindowTitle(_translate("auxWindow", "TEDS Sub-Block"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("auxWindow", "Field"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("auxWindow", "Value"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("auxWindow", "Include"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    auxWindow = QtWidgets.QMainWindow()
    ui = Ui_auxWindow()
    ui.setupUi(auxWindow)
    auxWindow.show()
    sys.exit(app.exec_())
